/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pp_PPNative */

#ifndef _Included_pp_PPNative
#define _Included_pp_PPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pp_PPNative
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Open
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Close
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    IsGameOver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_IsGameOver
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    GetMapSize
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_pp_PPNative_GetMapSize
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    GetStartPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_pp_PPNative_GetStartPosition
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    GetNumSpecialAreas
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_GetNumSpecialAreas
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    GetSpecialAreaPosition
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_pp_PPNative_GetSpecialAreaPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    GetResource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_GetResource
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    GetNumUnits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_GetNumUnits
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    GetUnitAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_GetUnitAt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetCoalition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1GetCoalition
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1GetType
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetPosition
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_pp_PPNative_Unit_1GetPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pp_PPNative_Unit_1GetHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetMaxHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_pp_PPNative_Unit_1GetMaxHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetGroup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1GetGroup
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_SetGroup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1SetGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_GetNumPdgCmds
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1GetNumPdgCmds
  (JNIEnv *, jclass, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_PdgCmd_GetCode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1PdgCmd_1GetCode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_PdgCmd_GetNumParams
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1PdgCmd_1GetNumParams
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_PdgCmd_GetParam
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_pp_PPNative_Unit_1PdgCmd_1GetParam
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_ActionOnUnit
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1ActionOnUnit
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     pp_PPNative
 * Method:    Unit_ActionOnPosition
 * Signature: (IIFF)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1ActionOnPosition
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     pp_PPNative
 * Method:    Unit_UntargetedAction
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_pp_PPNative_Unit_1UntargetedAction
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     pp_PPNative
 * Method:    GetError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pp_PPNative_GetError
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    ClearError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pp_PPNative_ClearError
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    EnterCriticalSection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pp_PPNative_EnterCriticalSection
  (JNIEnv *, jclass);

/*
 * Class:     pp_PPNative
 * Method:    ExitCriticalSection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pp_PPNative_ExitCriticalSection
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
